#!/usr/bin/env bash

./release
rsync -avz -e ssh -r release.n root@haxe-china.org:/var/www/haxe-china.org/app.n
rsync -avz -e ssh -r templates/* root@haxe-china.org:/var/www/haxe-china.org/templates
rsync -avz -e ssh -r public/* root@haxe-china.org:/var/www/haxe-china.org/public
