#!/usr/bin/env bash

./release
rsync -avz -e ssh -r app.n root@imcj.me:/vhost/haxe-china.org
rsync -avz -e ssh -r templates/* root@imcj.me:/vhost/haxe-china.org/templates
rsync -avz -e ssh -r public/* root@imcj.me:/vhost/haxe-china.org/public
